print('Hello,people')
print('Já oensou em fazer aconpanhamento/ atendiemnto clínico gratuito ?')
print('Na clínica de Dermatologia Idea, fazer esse serviço! Fazemos o acompanhamhamento de casos clínicos raros e gtratamentos de ouros casos')
print('Fazemos atendimentos para tratamentos de alguns casos, como :')
print('Dermatite Átopica;')
print('Hidradenite´s')
print('Psoríase;')
print('Dentre outros casos para medicamentos de auto-custo')
print('   Ficou interresado ou querendo saber mais dos nossos serviços?')
print(' Entre em contato e saiba mais!!!!')